create table if not exists public.negative_comment_alerts (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  platform text not null,
  post_url text not null,
  comment_id text,
  comment_text text not null,
  slack_channel_id text not null,
  slack_ts text,
  alerted_at timestamptz not null default now()
);

create index if not exists negative_comment_alerts_alerted_at_idx
  on public.negative_comment_alerts (alerted_at desc);

alter table public.negative_comment_alerts enable row level security;

-- The monitor uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
-- Do not expose this table to anon/authenticated roles.
