-- Meta Instagram 광고 댓글 Webhook 대기열.
-- Webhook 수신기는 광고 댓글(ad_id가 있는 comments 이벤트)만 저장하고,
-- 별도 GitHub Actions 작업이 분류/Slack 발송 후 processed_at을 기록한다.
create table if not exists public.meta_ad_comment_events (
  id bigint generated by default as identity primary key,
  comment_id text not null unique,
  ig_user_id text not null,
  media_id text,
  original_media_id text,
  ad_id text not null,
  ad_title text,
  username text,
  comment_text text not null,
  parent_comment_id text,
  event_time timestamptz,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_attempts integer not null default 0,
  last_error text
);

create index if not exists meta_ad_comment_events_pending_idx
  on public.meta_ad_comment_events (received_at asc)
  where processed_at is null;

alter table public.meta_ad_comment_events enable row level security;

-- Meta에서 생성된 알림만 서버 측 숨김 처리할 수 있도록 출처와 광고 식별자를 보존한다.
alter table public.negative_comment_alerts
  add column if not exists source text,
  add column if not exists meta_media_id text,
  add column if not exists meta_ad_id text;

create index if not exists negative_comment_alerts_source_idx
  on public.negative_comment_alerts (source);

-- 서비스 역할 키만 사용한다. anon/authenticated 정책은 만들지 않는다.

-- Rollback (데이터 삭제이므로 별도 승인 후 실행):
--   drop index if exists public.negative_comment_alerts_source_idx;
--   alter table public.negative_comment_alerts
--     drop column if exists meta_ad_id,
--     drop column if exists meta_media_id,
--     drop column if exists source;
--   drop table if exists public.meta_ad_comment_events;
